- hosts: insurance-app-test
  become: true

  tasks:
    - name: update repos
      apt:
        update_cache: yes

    - name: install docker
      apt:
        pkg: docker.io
        state: present

    - name: start docker
      service:
        name: docker
        state: started
        enabled: true

    - name: deploy insurance capstone application using container image
      command: docker run -itd -p 8081:8081 selvacse0304/capstone-app:1.0

